### ISSUE TITLE
The events are not working

### ISSUE THREAD

**Issue by jatasya** [Eastros/FrameCarousel#1]
Hi I'm trying to use events in order to acheive some variations in the other div. but I'm not getting and response from the event calls. I have tried using the code as below.

        $('.carousel_mobile').frameCarousel({
    debug:true,
    frame: 'Assets/iPhone_Mock.png',
    boundingBox: {
        left: '11.5%',
        top: '32.7%',
        width: '226px',
        height: '401px'
    },
    frameSize: [{
        width: 295,
        height:595
    }],
    controlsPosition: {
        top: '65%'
    },
    images: ['Assets/screen_mock_1.png',
             'Assets/screen_mock_2.png',
             'Assets/sceen_mock_3.png']
      });

       $('.carousel_mobile')
              .on('fc-ready', function( e ){
             alert(e);
              })

        .on('fc-transition-start', function( e ){
        // e.from => screen index from where transition begun
        // e.to   => screen index to where transition has to end
        alert(e.from);
        if(e.from == 0 && e.to == 1){
            $('#text_1').fadeOut('slow');
            $('#text_2').fadeIn('slow');
        }
    });

and I tried the below format also

    $('.carousel_mobile').frameCarousel({
    debug:true,
    frame: 'Assets/iPhone_Mock.png',
    boundingBox: {
        left: '11.5%',
        top: '32.7%',
        width: '226px',
        height: '401px'
    },
    frameSize: [{
        width: 295,
        height:595
    }],
    controlsPosition: {
        top: '65%'
    },
    images: ['Assets/screen_mock_1.png',
             'Assets/screen_mock_2.png',
             'Assets/sceen_mock_3.png']
       }) .on('fc-ready', function( e ){
          alert(e);
         })

        .on('fc-transition-start', function( e ){
        // e.from => screen index from where transition begun
        // e.to   => screen index to where transition has to end
        alert(e.from);
        if(e.from == 0 && e.to == 1){
            $('#text_1').fadeOut('slow');
            $('#text_2').fadeIn('slow');
        }
    });

**Comment by umarashfaq** [comment]
Have fixed the issue, let me know if it works for you now. Note that signature of callback functions for 'fc-transition-start' and 'fc-transition-end' should look like this (will update documentation):

```
$parent.on('fc-transition-start', function(e, from, to){

})
```
